#!/usr/bin/env python
import os
import sys

env = SConscript("godot-cpp/SConstruct")

# For reference:
# - CCFLAGS are compilation flags shared between C and C++
# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags

# tweak this if you want to use different folders, or more folders, to store your source code in.
env.Append(CPPPATH=["src/"])
# Compile C++ sources and the separate C file for stb_vorbis
sources = Glob("src/*.cpp") + Glob("src/stb_vorbis_wrapper.c")

# Platform-specific settings
if env["platform"] == "macos":
    library_name = "libminiaudio_decoder.{}.{}.framework/libminiaudio_decoder.{}.{}".format(
        env["platform"], env["target"], env["platform"], env["target"]
    )
    library = env.SharedLibrary(
        "bin/{}/{}".format(env["platform"], library_name),
        source=sources,
    )
else:
    library_name = "libminiaudio_decoder.{}.{}.{}{}".format(
        env["platform"], env["target"], env["arch"], env["SHLIBSUFFIX"]
    )
    library = env.SharedLibrary(
        "bin/{}/{}".format(env["platform"], library_name),
        source=sources,
    )

Default(library)
